CREATE DATABASE DeSo9_LuyenHaiDang

USE DeSo9_LuyenHaiDang

--Thiết kế CSDL--
CREATE TABLE Class

CREATE TABLE HeDaoTao
(
MAHDT CHAR(10) NOT NULL,
TENHDT NVARCHAR(50),
MOTA NCHAR(50),
CONSTRAINT PK_MAKHOA PRIMARY KEY(MAHDT)
)

CREATE TABLE ChuyenNganhDaoTao
(
MACNDT CHAR(10) NOT NULL,
TENCNDT NVARCHAR(50),
MOTA NCHAR(50),
CONSTRAINT PK_MACNDT PRIMARY KEY(MACNDT)
)

CREATE TABLE LopHoc
(
MALop CHAR(10) NOT NULL,
TENLop NVARCHAR(50),
SiSo INT,
MaHDT CHAR(10) FOREIGN KEY REFERENCES HeDaoTao(MAHDT) ON DELETE CASCADE ON UPDATE CASCADE,
MaCNDT CHAR(10) FOREIGN KEY REFERENCES ChuyenNganhDaoTao(MaCNDT) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PK_DIEMTHI PRIMARY KEY(MaLop),
)

drop table lophoc

--Tạo bảng Sinh Viên--
CREATE TABLE SINHVIEN(
MASV CHAR(10) NOT NULL,
HOTEN NVARCHAR(30),
NGAYSINH DATE CHECK(YEAR(NGAYSINH)<=1995 AND YEAR(NGAYSINH)>=1990),
GIOITINH BIT CHECK(GIOITINH IN (0,1)),
NOISINH NVARCHAR(30),
MALOP CHAR(10) FOREIGN KEY REFERENCES LopHoc(MALOP) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PK_MASV PRIMARY KEY(MASV)
)

--Tạo bảng Môn Học--
CREATE TABLE MONHOC(
MAMONHOC CHAR(10) NOT NULL,
TENMONHOC NVARCHAR(30),
SOTC INT CHECK(SOTC >=0 AND SOTC <=8),
CONSTRAINT PK_MONHOC PRIMARY KEY(MAMONHOC)
)

--Tạo bảng Môn Học--
CREATE TABLE LOPHOCLAICAITHIEN(
MALOP CHAR(10) NOT NULL,
TENLOP NVARCHAR(30),
MAMONHOC CHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMONHOC) ON DELETE CASCADE ON UPDATE CASCADE,
MAGV CHAR(10) FOREIGN KEY REFERENCES GIAOVIEN(MAGV) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PK_LICH PRIMARY KEY(MALOP)
)

drop table dangkyhoclai
drop table LOPHOCLAICAITHIEN
--Đăng ký học lại--
CREATE TABLE DANGKYHOCLAI(
MASV CHAR(10) FOREIGN KEY REFERENCES SINHVIEN(MASV) ON DELETE CASCADE ON UPDATE CASCADE,
MALOPHOCLAI CHAR(10) FOREIGN KEY REFERENCES LOPHOCLAICAITHIEN(MALOP) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PK_DKHL PRIMARY KEY(MaSV,MaLopHOCLAI)
)

drop table DANGKYHOCLAI
drop table lophoclaicaithien

drop table DANGKYHOCLAI


CREATE TABLE GIAOVIEN(
MASV CHAR(10) FOREIGN KEY REFERENCES SINHVIEN(MASV) ON DELETE CASCADE ON UPDATE CASCADE,
MAMH CHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMONHOC) ON DELETE CASCADE ON UPDATE CASCADE,
DIEMQT INT,
DIEMKTHP INT,
)


CREATE TABLE DIEMTHI(
MASV CHAR(10) FOREIGN KEY REFERENCES SINHVIEN(MASV) ON DELETE CASCADE ON UPDATE CASCADE,
MAMH CHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMONHOC) ON DELETE CASCADE ON UPDATE CASCADE,
DIEMQT INT,
DIEMKTHP INT,
CONSTRAINT PK_LIC PRIMARY KEY(MASV,MAMH)
)


