USE Deso9_LuyenHaiDang
CREATE DATABASE Deso9_LuyenHaiDang
--Tạo cơ sở dữ liệu--
--Tạo bảng chuyên ngành đào tạo--
CREATE TABLE TRAINING
(
IDTRAINING CHAR(10),
NAMETRANING NVARCHAR(50) UNIQUE,
DESCTRANING NVARCHAR(50),
CONSTRAINT PK_TRAINING PRIMARY KEY(IDTRAINING)
)

--Tạo bảng hệ đào tạo--
CREATE TABLE GENERATION
(
IDGENERATION CHAR(10),
NAMEGENERATION NVARCHAR(50) UNIQUE,
DESCGENERATION NVARCHAR(50),
CONSTRAINT PK_GENERATION PRIMARY KEY(IDGENERATION)
)

--Tạo bảng lớp học--
CREATE TABLE CLASS
(
IDCLASS CHAR(10),
NAMECLASS NVARCHAR(50) UNIQUE,
DESCGENERATION NVARCHAR(50),
SCHOOLYEAR NVARCHAR(50),
NUMBERSTUDENT INT,
IDTRAINING CHAR(10) FOREIGN KEY REFERENCES TRAINING(IDTRAINING) ON DELETE CASCADE ON UPDATE CASCADE,
IDGENERATION CHAR(10) FOREIGN KEY REFERENCES GENERATION(IDGENERATION) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PK_CLASS PRIMARY KEY(IDCLASS)
)

--Tạo bảng sinh viên--
CREATE TABLE STUDENT
(
IDSTUDENT CHAR(10),
NAMESTUDENT NVARCHAR(30),
BIRTHDAY DATE CHECK(YEAR(BIRTHDAY)<=1995 AND YEAR(BIRTHDAY)>=1990),
SEX NVARCHAR(3) CHECK(SEX IN (N'Nam',N'Nữ')),
ANDRESS NVARCHAR(30),
NUMBERPHONE NVARCHAR(10),
EMAIL NVARCHAR(30),
IDCLASS CHAR(10) FOREIGN KEY REFERENCES CLASS(IDCLASS) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PK_STUDENT PRIMARY KEY(IDSTUDENT)
)

--Tạo bảng giáo viên--
CREATE TABLE TEACHER
(
IDTEACHER CHAR(10),
NAMETEACHER NVARCHAR(30),
BIRTHDAY DATE CHECK(YEAR(BIRTHDAY)<=1995 AND YEAR(BIRTHDAY)>=1990),
SEX NVARCHAR(3) CHECK(SEX IN (N'Nam',N'Nữ')),
ANDRESS NVARCHAR(30),
NUMBERPHONE NVARCHAR(10),
EMAIL NVARCHAR(30),
CONSTRAINT PK_TEACHER PRIMARY KEY(IDTEACHER)
)
--Tạo bảng môn học--
CREATE TABLE SUBJECT
(
IDSUBJECT CHAR(10),
NAMESUBJECT NVARCHAR(30),
NUMBERCREDITS INT CHECK(NUMBERCREDITS > 0 AND NUMBERCREDITS < 16)
CONSTRAINT PK_SUBJECT PRIMARY KEY(IDSUBJECT)
)

--Tạo bảng lớp học cải thiện--
CREATE TABLE RETESTCLASS
(
IDCLASS CHAR(10),
NAMECLASS NVARCHAR(30),
IDSUBJECT CHAR(10) FOREIGN KEY REFERENCES SUBJECT(IDSUBJECT) ON DELETE CASCADE ON UPDATE CASCADE,
IDTEACHER CHAR(10) FOREIGN KEY REFERENCES TEACHER(IDTEACHER) ON DELETE CASCADE ON UPDATE CASCADE,
NUMBERSTUDENT INT,
STATUSRETESTCLASS NVARCHAR(30) CHECK(STATUSRETESTCLASS IN (N'ĐÓNG',N'MỞ')),
SEMESTER INT CHECK(SEMESTER >0 AND SEMESTER<3),
YEARSCHOOL NVARCHAR(30),
CONSTRAINT PK_RETESTCLASS PRIMARY KEY(IDCLASS)
)

--Tạo bảng đăng ký học lại--
CREATE TABLE REGISTERRETEST
(
IDREGISTERRETEST CHAR(10),
IDSTUDENT CHAR(10) FOREIGN KEY REFERENCES STUDENT(IDSTUDENT) ON DELETE CASCADE ON UPDATE CASCADE,
IDCLASS CHAR(10) FOREIGN KEY REFERENCES RETESTCLASS(IDCLASS) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT PK_REGISTERRETEST PRIMARY KEY(IDREGISTERRETEST)
)

ALTER TABLE REGISTERRETEST
--Tạo bảng nộp tiền--
CREATE TABLE SUMBILLREGISTERRETEST
(
IDREGISTERRETEST CHAR(10) FOREIGN KEY REFERENCES REGISTERRETEST(IDREGISTERRETEST) ON DELETE CASCADE ON UPDATE CASCADE,
SUMBILL INT,
STATUS NVARCHAR(30),
CONSTRAINT PK_SUMBILLREGISTERRETEST PRIMARY KEY(IDREGISTERRETEST)
)

CREATE TABLE BILLREGISTERRETEST(
IDREGISTERRETEST CHAR(10) FOREIGN KEY REFERENCES SUMBILLREGISTERRETEST(IDREGISTERRETEST) ON DELETE CASCADE ON UPDATE CASCADE,
BILL INT,
CONTENT NVARCHAR(50),
)

CREATE TABLE SCORESRETEST(
IDCLASS CHAR(10) FOREIGN KEY REFERENCES RETESTCLASS(IDCLASS) ON DELETE CASCADE ON UPDATE CASCADE,
IDSTUDENT CHAR(10) FOREIGN KEY REFERENCES STUDENT(IDSTUDENT) ON DELETE CASCADE ON UPDATE CASCADE,
MARK1 INT CHECK(MARK1>=0 AND MARK1<=10),
MARK2 INT CHECK(MARK2>=0 AND MARK2<=10)
)

CREATE TABLE SCORES(
IDSUBJECT CHAR(10) FOREIGN KEY REFERENCES SUBJECT(IDSUBJECT) ON DELETE CASCADE ON UPDATE CASCADE,
IDSTUDENT CHAR(10) FOREIGN KEY REFERENCES STUDENT(IDSTUDENT) ON DELETE CASCADE ON UPDATE CASCADE,
MARK1 INT CHECK(MARK1>=0 AND MARK1<=10),
MARK2 INT CHECK(MARK2>=0 AND MARK2<=10)
)
